language: csharp
solution: stun.sln
install:
  - nuget restore stun.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release stun.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./stun.Tests/bin/Release/stun.Tests.dll
